// vars types of dispatch

const VER_POPUP = "VER_POPUP";
const CERRAR_POPUP = "CERRAR_POPUP";
const USER_LOGGED = "USER_LOGGED";
const USER_LOGOUT = "USER_LOGOUT";
const TOKEN_INFO = "TOKEN_INFO";
const IS_ADMIN = "IS_ADMIN";
const SET_MOVIES = "SET_MOVIES";
const SHOW_POPUP = "SHOW_POPUP";
const CLOSE_POPUP = "CLOSE_POPUP";
const SHOW_LOADING = "SHOW_LOADING";
const CLOSE_LOADING = "CLOSE_LOADING"



export { VER_POPUP, CERRAR_POPUP, USER_LOGGED, USER_LOGOUT, TOKEN_INFO, IS_ADMIN, SET_MOVIES, CLOSE_POPUP, SHOW_POPUP, SHOW_LOADING, CLOSE_LOADING };
