// vars types of dispatch

const VER_POPUP = "VER_POPUP";
const CERRAR_POPUP = "CERRAR_POPUP";
const USER_LOGGED = "USER_LOGGED";
const USER_LOGOUT = "USER_LOGOUT";
const TOKEN_INFO = "TOKEN_INFO";



export { VER_POPUP, CERRAR_POPUP, USER_LOGGED, USER_LOGOUT, TOKEN_INFO };
